exports.seed = function ( knex, Promise ) {
    // Deletes ALL existing entries
    return knex( 'reviews' ).del()
        .then( function () {
            // Inserts seed entries
            return knex( 'reviews' ).insert( [
                {
                    appearance: 7,
                    taste: 7,
                    smell: 7,
                    effect: 7,
                    recommend: 7,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 1
              }, {
                    appearance: 5,
                    taste: 9,
                    smell: 3,
                    effect: 9,
                    recommend: 5,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 5,
                    taste: 6,
                    smell: 5,
                    effect: 6,
                    recommend: 5,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 4,
                    taste: 5,
                    smell: 4,
                    effect: 5,
                    recommend: 4,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 8,
                    taste: 7,
                    smell: 8,
                    effect: 7,
                    recommend: 8,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 9,
                    taste: 8,
                    smell: 9,
                    effect: 8,
                    recommend: 9,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 7,
                    taste: 8,
                    smell: 7,
                    effect: 8,
                    recommend: 7,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 9,
                    taste: 9,
                    smell: 9,
                    effect: 9,
                    recommend: 9,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 7,
                    taste: 7,
                    smell: 7,
                    effect: 7,
                    recommend: 7,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 4,
                    taste: 4,
                    smell: 4,
                    effect: 4,
                    recommend: 4,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 1,
                    taste: 1,
                    smell: 1,
                    effect: 1,
                    recommend: 1,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 5,
                    taste: 5,
                    smell: 7,
                    effect: 7,
                    recommend: 5,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 8,
                    taste: 7,
                    smell: 6,
                    effect: 4,
                    recommend: 4,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 6,
                    taste: 6,
                    smell: 6,
                    effect: 10,
                    recommend: 10,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 9,
                    taste: 4,
                    smell: 7,
                    effect: 7,
                    recommend: 6,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 8,
                    taste: 8,
                    smell: 6,
                    effect: 8,
                    recommend: 9,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 6,
                    taste: 6,
                    smell: 6,
                    effect: 8,
                    recommend: 7,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 5,
                    taste: 5,
                    smell: 4,
                    effect: 4,
                    recommend: 4,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 1,
                    taste: 1,
                    smell: 1,
                    effect: 1,
                    recommend: 1,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }, {
                    appearance: 7,
                    taste: 6,
                    smell: 6,
                    effect: 9,
                    recommend: 9,
                    from: '',
                    share: false,
                    product_id: 3,
                    user_id: 2
              }
              ] );
        } );
};